name: Provisioning-Service

on: 
  push:
    paths:
      - 'src/provisioning/CatenaX.NetworkServices.Provisioning.Service/**'

    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/Dockerfile.provisioning
          tags: ghcr.io/${{ github.actor }}/provisioning-service:latest